apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: egresses.egress.loxilb.io
spec:
  group: egress.loxilb.io
  names:
    kind: Egress
    listKind: EgressList
    plural: egresses
    singular: egress
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: EgressSpec defines the desired state of Egress
              type: object
              properties:
                addresses:
                  type: array
                  items:
                    type: string
                vip:
                  type: string
                selector:
                  additionalProperties:
                    type: string
                  type: object
            status:
              description: EgressStatus defines the observed state of Egress
              type: object
      subresources:
        status: {}      