name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'
        required: true
        default: 'latest'

jobs:
  build:
    name: build-ci

    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - uses: actions/setup-go@v3
      with:
          go-version: '>=1.19.0'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Try to build the kube-loxilb image
      run: make

    - name: Try to build the kube-loxilb docker image
      run: docker build . --tag ghcr.io/loxilb-io/kube-loxilb:latest
